### ISSUE TITLE
Child route events duplicated with jQuery

### ISSUE THREAD

**Issue by danjford** [stoodder/finchjs#26]
If I navigate from one child route to another child route, maybe of a different id for a blog post, then the click events are now duplicated and will fire twice. 

Is there a way to have it in Finch so that the events for that child route are removed and re-added or just not duplicated?

Was looking for a cleaner solution then adding code everywhere which is unbinding and rebinding events.

```
Finch.route("/blog", function(bindings) {
  return console.log("Setup the home route");
});

Finch.route("[/blog]/:id", function(bindings) {
   $('#link').on('click', function(){
       console.log('click event will be hit twice');
   });
});
```

**Comment by stoodder** [comment]
@danjford Finch has a concept of setup, load, unload and teardown that you can specify when defining a route.  So, in your scenario you'd want to have something like this:

```
Finch.route("/blog", function(bindings) {
  return console.log("Setup the home route");
});

Finch.route("[/blog]/:id", {
	load: function(bindings) {
		$('#link').on('click', function(){
			console.log('click event will be hit twice');
		});
	},
	
	unload: function(bindings) {
		$('#link').off('click')
	}
});
```

`setup` is called whenever a route is passed through, `load` is called when a route is a direct match, `unload` is called when the route changes, and `teardown` is called when the route changes and will end at a different route definition.  So, given something like this:

```
Finch.route("/blog", {
	setup: function(bindings) {
		return console.log("Setup the home route");
	},
	load: function(bindings) {
		return console.log("Loaded the home route");
	},
	unload: function(bindings) {
		return console.log("Unloaded the home route");
	},
	teardown: function(bindings) {
		return console.log("Teardown the home route");
	}
});

Finch.route("[/blog]/:id", {
	setup: function(bindings) {
		return console.log("Setup the blog route with id: " + bindings.id);
	},
	load: function(bindings) {
		return console.log("Loaded the blog route with id: " + bindings.id);
	},
	unload: function(bindings) {
		return console.log("Unloaded the blog route with id: " + bindings.id);
	},
	teardown: function(bindings) {
		return console.log("Teardown the blog route with id: " + bindings.id);
	}
});
```

If you called `/blog/3` in your console you should see:
```
Setup the home route
Setup the blog route with id: 3
Loaded the bog route with id: 3
```

And from there, calling `/blog/4` would show:
```
Unloaded the blog route with id: 3
Loaded the bog route with id: 4
```

And lastly, calling `/blog` from there would show:
```
Unloaded the blog route with id: 4
Teardown the bog route with id: 4
Loaded the home route
```

Hope that makes sense!

**Comment by danjford** [comment]
@stoodder thanks for your reply, is there a way to make it so that all click events are generically removed without needing to specify the exact element and without negatively affecting e.g. click events in the parent?

**Comment by stoodder** [comment]
@danjford There's no way for click events to generically remove themselves. The best way to do this would be to do somehting like this:

```
Finch.route("[/blog]/:id", {
    load: function(bindings) {
		this.onclick = function(){
            console.log('click event will be hit twice');
        };
		
        $('#link').on('click', this.onclick);
    },

    unload: function(bindings) {
        $('#link').off('click', this.onclick);
    }
});
```
