### ISSUE TITLE
Hashbangs in Finch

### ISSUE THREAD

**Issue by danjford** [stoodder/finchjs#27]
Just wondering if Finch had something inbuilt or if there was an easy way to use hashbangs (#!) instead of hashes by themselves in finch?

**Comment by stoodder** [comment]
@danjford I actually have a new version of Finch being released which supports hashbangs. It works just like this version of Finch, if you'd like i can set you up with an edge version of that

**Comment by stoodder** [comment]
@danjford You can take a look here if you're interested: https://github.com/stoodder/finchjs/tree/rewrite
